#ifndef ENUMERATION_H
#define ENUMERATION_H

enum STATE{NORMAL,SLEEP,POISON,VERTIGO,DEATH};
enum RACE{HUMAN,ORC,NIGHYELF,UNDEAD};
enum TYPE{SKILL,CONSUMABLE,EQUIPMENT};
enum CAMP {Allies, Enemy ,MAX_CAMP_NUM, Empty,};//友方阵营还是敌方阵营

#endif